### ISSUE TITLE
`${^TYPE_PARAMS_MULTISIG}` is deprecated

### ISSUE THREAD

**Issue by tobyink** [cxw42/Sub-Multi-Tiny#10]
https://github.com/cxw42/Sub-Multi-Tiny/blob/fe37e9bc8de4cb4d35092647d7cb41c07bf5f09f/lib/Sub/Multi/Tiny/Dispatcher/TypeParams.pm#L134

`${^_TYPE_PARAMS_MULTISIG}` (with an extra underscore) is its replacement in Type::Params v2.

`${^TYPE_PARAMS_MULTISIG}` is still supported, but support will be removed in about six months.

This is because the next version of the Perl may introduce new warnings or errors related to these variables. See https://github.com/Perl/RFCs/pull/22.

**Comment by cxw42** [comment]
@tobyink Thanks for the heads-up!

**Comment by cxw42** [comment]
Fixed in v0.000013 :)
